Fix type error applying len() on int (change number)
We got an error when running git review --list:
TypeError: object of type 'int' has no len()
because change number is represented as integer.